export const DISTRICT = [
    { label: 'Ba Đình', value: '001', provinceId: '01', cap: 'Quận' },
    { label: 'Hoàn Kiếm', value: '002', provinceId: '01', cap: 'Quận' },
    { label: 'Tây Hồ', value: '003', provinceId: '01', cap: 'Quận' },
    { label: 'Long Biên', value: '004', provinceId: '01', cap: 'Quận' },
    { label: 'Cầu Giấy', value: '005', provinceId: '01', cap: 'Quận' },
    { label: 'Đống Đa', value: '006', provinceId: '01', cap: 'Quận' },
    { label: 'Hai Bà Trưng', value: '007', provinceId: '01', cap: 'Quận' },
    { label: 'Hoàng Mai', value: '008', provinceId: '01', cap: 'Quận' },
    { label: 'Thanh Xuân', value: '009', provinceId: '01', cap: 'Quận' },
    { label: 'Sóc Sơn', value: '016', provinceId: '01', cap: 'Huyện' },
    { label: 'Đông Anh', value: '017', provinceId: '01', cap: 'Huyện' },
    { label: 'Gia Lâm', value: '018', provinceId: '01', cap: 'Huyện' },
    { label: 'Nam Từ Liêm', value: '019', provinceId: '01', cap: 'Quận' },
    { label: 'Thanh Trì', value: '020', provinceId: '01', cap: 'Huyện' },
    { label: 'Bắc Từ Liêm', value: '021', provinceId: '01', cap: 'Quận' },
    { label: 'Hà Giang', value: '024', provinceId: '02', cap: 'Thành phố' },
    { label: 'Đồng Văn', value: '026', provinceId: '02', cap: 'Huyện' },
    { label: 'Mèo Vạc', value: '027', provinceId: '02', cap: 'Huyện' },
    { label: 'Yên Minh', value: '028', provinceId: '02', cap: 'Huyện' },
    { label: 'Quản Bạ', value: '029', provinceId: '02', cap: 'Huyện' },
    { label: 'Vị Xuyên', value: '030', provinceId: '02', cap: 'Huyện' },
    { label: 'Bắc Mê', value: '031', provinceId: '02', cap: 'Huyện' },
    { label: 'Hoàng Su Phì', value: '032', provinceId: '02', cap: 'Huyện' },
    { label: 'Xín Mần', value: '033', provinceId: '02', cap: 'Huyện' },
    { label: 'Bắc Quang', value: '034', provinceId: '02', cap: 'Huyện' },
    { label: 'Quang Bình', value: '035', provinceId: '02', cap: 'Huyện' },
    { label: 'Cao Bằng', value: '040', provinceId: '04', cap: 'Thành phố' },
    { label: 'Bảo Lâm', value: '042', provinceId: '04', cap: 'Huyện' },
    { label: 'Bảo Lạc', value: '043', provinceId: '04', cap: 'Huyện' },
    { label: 'Hà Quảng', value: '045', provinceId: '04', cap: 'Huyện' },
    { label: 'Trùng Khánh', value: '047', provinceId: '04', cap: 'Huyện' },
    { label: 'Hạ Lang', value: '048', provinceId: '04', cap: 'Huyện' },
    { label: 'Quảng Hòa', value: '049', provinceId: '04', cap: 'Huyện' },
    { label: 'Hoà An', value: '051', provinceId: '04', cap: 'Huyện' },
    { label: 'Nguyên Bình', value: '052', provinceId: '04', cap: 'Huyện' },
    { label: 'Thạch An', value: '053', provinceId: '04', cap: 'Huyện' },
    { label: 'Bắc Kạn', value: '058', provinceId: '06', cap: 'Thành phố' },
    { label: 'Pác Nặm', value: '060', provinceId: '06', cap: 'Huyện' },
    { label: 'Ba Bể', value: '061', provinceId: '06', cap: 'Huyện' },
    { label: 'Ngân Sơn', value: '062', provinceId: '06', cap: 'Huyện' },
    { label: 'Bạch Thông', value: '063', provinceId: '06', cap: 'Huyện' },
    { label: 'Chợ Đồn', value: '064', provinceId: '06', cap: 'Huyện' },
    { label: 'Chợ Mới', value: '065', provinceId: '06', cap: 'Huyện' },
    { label: 'Na Rì', value: '066', provinceId: '06', cap: 'Huyện' },
    { label: 'Tuyên Quang', value: '070', provinceId: '08', cap: 'Thành phố' },
    { label: 'Lâm Bình', value: '071', provinceId: '08', cap: 'Huyện' },
    { label: 'Na Hang', value: '072', provinceId: '08', cap: 'Huyện' },
    { label: 'Chiêm Hóa', value: '073', provinceId: '08', cap: 'Huyện' },
    { label: 'Hàm Yên', value: '074', provinceId: '08', cap: 'Huyện' },
    { label: 'Yên Sơn', value: '075', provinceId: '08', cap: 'Huyện' },
    { label: 'Sơn Dương', value: '076', provinceId: '08', cap: 'Huyện' },
    { label: 'Lào Cai', value: '080', provinceId: '10', cap: 'Thành phố' },
    { label: 'Bát Xát', value: '082', provinceId: '10', cap: 'Huyện' },
    { label: 'Mường Khương', value: '083', provinceId: '10', cap: 'Huyện' },
    { label: 'Si Ma Cai', value: '084', provinceId: '10', cap: 'Huyện' },
    { label: 'Bắc Hà', value: '085', provinceId: '10', cap: 'Huyện' },
    { label: 'Bảo Thắng', value: '086', provinceId: '10', cap: 'Huyện' },
    { label: 'Bảo Yên', value: '087', provinceId: '10', cap: 'Huyện' },
    { label: 'Sa Pa', value: '088', provinceId: '10', cap: 'Thị xã' },
    { label: 'Văn Bàn', value: '089', provinceId: '10', cap: 'Huyện' },
    { label: 'Điện Biên Phủ', value: '094', provinceId: '11', cap: 'Thành phố' },
    { label: 'Mường Lay', value: '095', provinceId: '11', cap: 'Thị xã' },
    { label: 'Mường Nhé', value: '096', provinceId: '11', cap: 'Huyện' },
    { label: 'Mường Chà', value: '097', provinceId: '11', cap: 'Huyện' },
    { label: 'Tủa Chùa', value: '098', provinceId: '11', cap: 'Huyện' },
    { label: 'Tuần Giáo', value: '099', provinceId: '11', cap: 'Huyện' },
    { label: 'Điện Biên', value: '100', provinceId: '11', cap: 'Huyện' },
    { label: 'Điện Biên Đông', value: '101', provinceId: '11', cap: 'Huyện' },
    { label: 'Mường Ảng', value: '102', provinceId: '11', cap: 'Huyện' },
    { label: 'Nậm Pồ', value: '103', provinceId: '11', cap: 'Huyện' },
    { label: 'Lai Châu', value: '105', provinceId: '12', cap: 'Thành phố' },
    { label: 'Tam Đường', value: '106', provinceId: '12', cap: 'Huyện' },
    { label: 'Mường Tè', value: '107', provinceId: '12', cap: 'Huyện' },
    { label: 'Sìn Hồ', value: '108', provinceId: '12', cap: 'Huyện' },
    { label: 'Phong Thổ', value: '109', provinceId: '12', cap: 'Huyện' },
    { label: 'Than Uyên', value: '110', provinceId: '12', cap: 'Huyện' },
    { label: 'Tân Uyên', value: '111', provinceId: '12', cap: 'Huyện' },
    { label: 'Nậm Nhùn', value: '112', provinceId: '12', cap: 'Huyện' },
    { label: 'Sơn La', value: '116', provinceId: '14', cap: 'Thành phố' },
    { label: 'Quỳnh Nhai', value: '118', provinceId: '14', cap: 'Huyện' },
    { label: 'Thuận Châu', value: '119', provinceId: '14', cap: 'Huyện' },
    { label: 'Mường La', value: '120', provinceId: '14', cap: 'Huyện' },
    { label: 'Bắc Yên', value: '121', provinceId: '14', cap: 'Huyện' },
    { label: 'Phù Yên', value: '122', provinceId: '14', cap: 'Huyện' },
    { label: 'Mộc Châu', value: '123', provinceId: '14', cap: 'Huyện' },
    { label: 'Yên Châu', value: '124', provinceId: '14', cap: 'Huyện' },
    { label: 'Mai Sơn', value: '125', provinceId: '14', cap: 'Huyện' },
    { label: 'Sông Mã', value: '126', provinceId: '14', cap: 'Huyện' },
    { label: 'Sốp Cộp', value: '127', provinceId: '14', cap: 'Huyện' },
    { label: 'Vân Hồ', value: '128', provinceId: '14', cap: 'Huyện' },
    { label: 'Yên Bái', value: '132', provinceId: '15', cap: 'Thành phố' },
    { label: 'Nghĩa Lộ', value: '133', provinceId: '15', cap: 'Thị xã' },
    { label: 'Lục Yên', value: '135', provinceId: '15', cap: 'Huyện' },
    { label: 'Văn Yên', value: '136', provinceId: '15', cap: 'Huyện' },
    { label: 'Mù Căng Chải', value: '137', provinceId: '15', cap: 'Huyện' },
    { label: 'Trấn Yên', value: '138', provinceId: '15', cap: 'Huyện' },
    { label: 'Trạm Tấu', value: '139', provinceId: '15', cap: 'Huyện' },
    { label: 'Văn Chấn', value: '140', provinceId: '15', cap: 'Huyện' },
    { label: 'Yên Bình', value: '141', provinceId: '15', cap: 'Huyện' },
    { label: 'Hòa Bình', value: '148', provinceId: '17', cap: 'Thành phố' },
    { label: 'Đà Bắc', value: '150', provinceId: '17', cap: 'Huyện' },
    { label: 'Lương Sơn', value: '152', provinceId: '17', cap: 'Huyện' },
    { label: 'Kim Bôi', value: '153', provinceId: '17', cap: 'Huyện' },
    { label: 'Cao Phong', value: '154', provinceId: '17', cap: 'Huyện' },
    { label: 'Tân Lạc', value: '155', provinceId: '17', cap: 'Huyện' },
    { label: 'Mai Châu', value: '156', provinceId: '17', cap: 'Huyện' },
    { label: 'Lạc Sơn', value: '157', provinceId: '17', cap: 'Huyện' },
    { label: 'Yên Thủy', value: '158', provinceId: '17', cap: 'Huyện' },
    { label: 'Lạc Thủy', value: '159', provinceId: '17', cap: 'Huyện' },
    { label: 'Thái Nguyên', value: '164', provinceId: '19', cap: 'Thành phố' },
    { label: 'Sông Công', value: '165', provinceId: '19', cap: 'Thành phố' },
    { label: 'Định Hóa', value: '167', provinceId: '19', cap: 'Huyện' },
    { label: 'Phú Lương', value: '168', provinceId: '19', cap: 'Huyện' },
    { label: 'Đồng Hỷ', value: '169', provinceId: '19', cap: 'Huyện' },
    { label: 'Võ Nhai', value: '170', provinceId: '19', cap: 'Huyện' },
    { label: 'Đại Từ', value: '171', provinceId: '19', cap: 'Huyện' },
    { label: 'Phổ Yên', value: '172', provinceId: '19', cap: 'Thị xã' },
    { label: 'Phú Bình', value: '173', provinceId: '19', cap: 'Huyện' },
    { label: 'Lạng Sơn', value: '178', provinceId: '20', cap: 'Thành phố' },
    { label: 'Tràng Định', value: '180', provinceId: '20', cap: 'Huyện' },
    { label: 'Bình Gia', value: '181', provinceId: '20', cap: 'Huyện' },
    { label: 'Văn Lãng', value: '182', provinceId: '20', cap: 'Huyện' },
    { label: 'Cao Lộc', value: '183', provinceId: '20', cap: 'Huyện' },
    { label: 'Văn Quan', value: '184', provinceId: '20', cap: 'Huyện' },
    { label: 'Bắc Sơn', value: '185', provinceId: '20', cap: 'Huyện' },
    { label: 'Hữu Lũng', value: '186', provinceId: '20', cap: 'Huyện' },
    { label: 'Chi Lăng', value: '187', provinceId: '20', cap: 'Huyện' },
    { label: 'Lộc Bình', value: '188', provinceId: '20', cap: 'Huyện' },
    { label: 'Đình Lập', value: '189', provinceId: '20', cap: 'Huyện' },
    { label: 'Hạ Long', value: '193', provinceId: '22', cap: 'Thành phố' },
    { label: 'Móng Cái', value: '194', provinceId: '22', cap: 'Thành phố' },
    { label: 'Cẩm Phả', value: '195', provinceId: '22', cap: 'Thành phố' },
    { label: 'Uông Bí', value: '196', provinceId: '22', cap: 'Thành phố' },
    { label: 'Bình Liêu', value: '198', provinceId: '22', cap: 'Huyện' },
    { label: 'Tiên Yên', value: '199', provinceId: '22', cap: 'Huyện' },
    { label: 'Đầm Hà', value: '200', provinceId: '22', cap: 'Huyện' },
    { label: 'Hải Hà', value: '201', provinceId: '22', cap: 'Huyện' },
    { label: 'Ba Chẽ', value: '202', provinceId: '22', cap: 'Huyện' },
    { label: 'Vân Đồn', value: '203', provinceId: '22', cap: 'Huyện' },
    { label: 'Đông Triều', value: '205', provinceId: '22', cap: 'Thị xã' },
    { label: 'Quảng Yên', value: '206', provinceId: '22', cap: 'Thị xã' },
    { label: 'Cô Tô', value: '207', provinceId: '22', cap: 'Huyện' },
    { label: 'Bắc Giang', value: '213', provinceId: '24', cap: 'Thành phố' },
    { label: 'Yên Thế', value: '215', provinceId: '24', cap: 'Huyện' },
    { label: 'Tân Yên', value: '216', provinceId: '24', cap: 'Huyện' },
    { label: 'Lạng Giang', value: '217', provinceId: '24', cap: 'Huyện' },
    { label: 'Lục Nam', value: '218', provinceId: '24', cap: 'Huyện' },
    { label: 'Lục Ngạn', value: '219', provinceId: '24', cap: 'Huyện' },
    { label: 'Sơn Động', value: '220', provinceId: '24', cap: 'Huyện' },
    { label: 'Yên Dũng', value: '221', provinceId: '24', cap: 'Huyện' },
    { label: 'Việt Yên', value: '222', provinceId: '24', cap: 'Huyện' },
    { label: 'Hiệp Hòa', value: '223', provinceId: '24', cap: 'Huyện' },
    { label: 'Việt Trì', value: '227', provinceId: '25', cap: 'Thành phố' },
    { label: 'Phú Thọ', value: '228', provinceId: '25', cap: 'Thị xã' },
    { label: 'Đoan Hùng', value: '230', provinceId: '25', cap: 'Huyện' },
    { label: 'Hạ Hoà', value: '231', provinceId: '25', cap: 'Huyện' },
    { label: 'Thanh Ba', value: '232', provinceId: '25', cap: 'Huyện' },
    { label: 'Phù Ninh', value: '233', provinceId: '25', cap: 'Huyện' },
    { label: 'Yên Lập', value: '234', provinceId: '25', cap: 'Huyện' },
    { label: 'Cẩm Khê', value: '235', provinceId: '25', cap: 'Huyện' },
    { label: 'Tam Nông', value: '236', provinceId: '25', cap: 'Huyện' },
    { label: 'Lâm Thao', value: '237', provinceId: '25', cap: 'Huyện' },
    { label: 'Thanh Sơn', value: '238', provinceId: '25', cap: 'Huyện' },
    { label: 'Thanh Thuỷ', value: '239', provinceId: '25', cap: 'Huyện' },
    { label: 'Tân Sơn', value: '240', provinceId: '25', cap: 'Huyện' },
    { label: 'Vĩnh Yên', value: '243', provinceId: '26', cap: 'Thành phố' },
    { label: 'Phúc Yên', value: '244', provinceId: '26', cap: 'Thành phố' },
    { label: 'Lập Thạch', value: '246', provinceId: '26', cap: 'Huyện' },
    { label: 'Tam Dương', value: '247', provinceId: '26', cap: 'Huyện' },
    { label: 'Tam Đảo', value: '248', provinceId: '26', cap: 'Huyện' },
    { label: 'Bình Xuyên', value: '249', provinceId: '26', cap: 'Huyện' },
    { label: 'Mê Linh', value: '250', provinceId: '01', cap: 'Huyện' },
    { label: 'Yên Lạc', value: '251', provinceId: '26', cap: 'Huyện' },
    { label: 'Vĩnh Tường', value: '252', provinceId: '26', cap: 'Huyện' },
    { label: 'Sông Lô', value: '253', provinceId: '26', cap: 'Huyện' },
    { label: 'Bắc Ninh', value: '256', provinceId: '27', cap: 'Thành phố' },
    { label: 'Yên Phong', value: '258', provinceId: '27', cap: 'Huyện' },
    { label: 'Quế Võ', value: '259', provinceId: '27', cap: 'Huyện' },
    { label: 'Tiên Du', value: '260', provinceId: '27', cap: 'Huyện' },
    { label: 'Từ Sơn', value: '261', provinceId: '27', cap: 'Thị xã' },
    { label: 'Thuận Thành', value: '262', provinceId: '27', cap: 'Huyện' },
    { label: 'Gia Bình', value: '263', provinceId: '27', cap: 'Huyện' },
    { label: 'Lương Tài', value: '264', provinceId: '27', cap: 'Huyện' },
    { label: 'Hà Đông', value: '268', provinceId: '01', cap: 'Quận' },
    { label: 'Sơn Tây', value: '269', provinceId: '01', cap: 'Thị xã' },
    { label: 'Ba Vì', value: '271', provinceId: '01', cap: 'Huyện' },
    { label: 'Phúc Thọ', value: '272', provinceId: '01', cap: 'Huyện' },
    { label: 'Đan Phượng', value: '273', provinceId: '01', cap: 'Huyện' },
    { label: 'Hoài Đức', value: '274', provinceId: '01', cap: 'Huyện' },
    { label: 'Quốc Oai', value: '275', provinceId: '01', cap: 'Huyện' },
    { label: 'Thạch Thất', value: '276', provinceId: '01', cap: 'Huyện' },
    { label: 'Chương Mỹ', value: '277', provinceId: '01', cap: 'Huyện' },
    { label: 'Thanh Oai', value: '278', provinceId: '01', cap: 'Huyện' },
    { label: 'Thường Tín', value: '279', provinceId: '01', cap: 'Huyện' },
    { label: 'Phú Xuyên', value: '280', provinceId: '01', cap: 'Huyện' },
    { label: 'Ứng Hòa', value: '281', provinceId: '01', cap: 'Huyện' },
    { label: 'Mỹ Đức', value: '282', provinceId: '01', cap: 'Huyện' },
    { label: 'Hải Dương', value: '288', provinceId: '30', cap: 'Thành phố' },
    { label: 'Chí Linh', value: '290', provinceId: '30', cap: 'Thành phố' },
    { label: 'Nam Sách', value: '291', provinceId: '30', cap: 'Huyện' },
    { label: 'Kinh Môn', value: '292', provinceId: '30', cap: 'Thị xã' },
    { label: 'Kim Thành', value: '293', provinceId: '30', cap: 'Huyện' },
    { label: 'Thanh Hà', value: '294', provinceId: '30', cap: 'Huyện' },
    { label: 'Cẩm Giàng', value: '295', provinceId: '30', cap: 'Huyện' },
    { label: 'Bình Giang', value: '296', provinceId: '30', cap: 'Huyện' },
    { label: 'Gia Lộc', value: '297', provinceId: '30', cap: 'Huyện' },
    { label: 'Tứ Kỳ', value: '298', provinceId: '30', cap: 'Huyện' },
    { label: 'Ninh Giang', value: '299', provinceId: '30', cap: 'Huyện' },
    { label: 'Thanh Miện', value: '300', provinceId: '30', cap: 'Huyện' },
    { label: 'Hồng Bàng', value: '303', provinceId: '31', cap: 'Quận' },
    { label: 'Ngô Quyền', value: '304', provinceId: '31', cap: 'Quận' },
    { label: 'Lê Chân', value: '305', provinceId: '31', cap: 'Quận' },
    { label: 'Hải An', value: '306', provinceId: '31', cap: 'Quận' },
    { label: 'Kiến An', value: '307', provinceId: '31', cap: 'Quận' },
    { label: 'Đồ Sơn', value: '308', provinceId: '31', cap: 'Quận' },
    { label: 'Dương Kinh', value: '309', provinceId: '31', cap: 'Quận' },
    { label: 'Thuỷ Nguyên', value: '311', provinceId: '31', cap: 'Huyện' },
    { label: 'An Dương', value: '312', provinceId: '31', cap: 'Huyện' },
    { label: 'An Lão', value: '313', provinceId: '31', cap: 'Huyện' },
    { label: 'Kiến Thuỵ', value: '314', provinceId: '31', cap: 'Huyện' },
    { label: 'Tiên Lãng', value: '315', provinceId: '31', cap: 'Huyện' },
    { label: 'Vĩnh Bảo', value: '316', provinceId: '31', cap: 'Huyện' },
    { label: 'Cát Hải', value: '317', provinceId: '31', cap: 'Huyện' },
    { label: 'Bạch Long Vĩ', value: '318', provinceId: '31', cap: 'Huyện' },
    { label: 'Hưng Yên', value: '323', provinceId: '33', cap: 'Thành phố' },
    { label: 'Văn Lâm', value: '325', provinceId: '33', cap: 'Huyện' },
    { label: 'Văn Giang', value: '326', provinceId: '33', cap: 'Huyện' },
    { label: 'Yên Mỹ', value: '327', provinceId: '33', cap: 'Huyện' },
    { label: 'Mỹ Hào', value: '328', provinceId: '33', cap: 'Thị xã' },
    { label: 'Ân Thi', value: '329', provinceId: '33', cap: 'Huyện' },
    { label: 'Khoái Châu', value: '330', provinceId: '33', cap: 'Huyện' },
    { label: 'Kim Động', value: '331', provinceId: '33', cap: 'Huyện' },
    { label: 'Tiên Lữ', value: '332', provinceId: '33', cap: 'Huyện' },
    { label: 'Phù Cừ', value: '333', provinceId: '33', cap: 'Huyện' },
    { label: 'Thái Bình', value: '336', provinceId: '34', cap: 'Thành phố' },
    { label: 'Quỳnh Phụ', value: '338', provinceId: '34', cap: 'Huyện' },
    { label: 'Hưng Hà', value: '339', provinceId: '34', cap: 'Huyện' },
    { label: 'Đông Hưng', value: '340', provinceId: '34', cap: 'Huyện' },
    { label: 'Thái Thụy', value: '341', provinceId: '34', cap: 'Huyện' },
    { label: 'Tiền Hải', value: '342', provinceId: '34', cap: 'Huyện' },
    { label: 'Kiến Xương', value: '343', provinceId: '34', cap: 'Huyện' },
    { label: 'Vũ Thư', value: '344', provinceId: '34', cap: 'Huyện' },
    { label: 'Phủ Lý', value: '347', provinceId: '35', cap: 'Thành phố' },
    { label: 'Duy Tiên', value: '349', provinceId: '35', cap: 'Thị xã' },
    { label: 'Kim Bảng', value: '350', provinceId: '35', cap: 'Huyện' },
    { label: 'Thanh Liêm', value: '351', provinceId: '35', cap: 'Huyện' },
    { label: 'Bình Lục', value: '352', provinceId: '35', cap: 'Huyện' },
    { label: 'Lý Nhân', value: '353', provinceId: '35', cap: 'Huyện' },
    { label: 'Nam Định', value: '356', provinceId: '36', cap: 'Thành phố' },
    { label: 'Mỹ Lộc', value: '358', provinceId: '36', cap: 'Huyện' },
    { label: 'Vụ Bản', value: '359', provinceId: '36', cap: 'Huyện' },
    { label: 'Ý Yên', value: '360', provinceId: '36', cap: 'Huyện' },
    { label: 'Nghĩa Hưng', value: '361', provinceId: '36', cap: 'Huyện' },
    { label: 'Nam Trực', value: '362', provinceId: '36', cap: 'Huyện' },
    { label: 'Trực Ninh', value: '363', provinceId: '36', cap: 'Huyện' },
    { label: 'Xuân Trường', value: '364', provinceId: '36', cap: 'Huyện' },
    { label: 'Giao Thủy', value: '365', provinceId: '36', cap: 'Huyện' },
    { label: 'Hải Hậu', value: '366', provinceId: '36', cap: 'Huyện' },
    { label: 'Ninh Bình', value: '369', provinceId: '37', cap: 'Thành phố' },
    { label: 'Tam Điệp', value: '370', provinceId: '37', cap: 'Thành phố' },
    { label: 'Nho Quan', value: '372', provinceId: '37', cap: 'Huyện' },
    { label: 'Gia Viễn', value: '373', provinceId: '37', cap: 'Huyện' },
    { label: 'Hoa Lư', value: '374', provinceId: '37', cap: 'Huyện' },
    { label: 'Yên Khánh', value: '375', provinceId: '37', cap: 'Huyện' },
    { label: 'Kim Sơn', value: '376', provinceId: '37', cap: 'Huyện' },
    { label: 'Yên Mô', value: '377', provinceId: '37', cap: 'Huyện' },
    { label: 'Thanh Hóa', value: '380', provinceId: '38', cap: 'Thành phố' },
    { label: 'Bỉm Sơn', value: '381', provinceId: '38', cap: 'Thị xã' },
    { label: 'Sầm Sơn', value: '382', provinceId: '38', cap: 'Thành phố' },
    { label: 'Mường Lát', value: '384', provinceId: '38', cap: 'Huyện' },
    { label: 'Quan Hóa', value: '385', provinceId: '38', cap: 'Huyện' },
    { label: 'Bá Thước', value: '386', provinceId: '38', cap: 'Huyện' },
    { label: 'Quan Sơn', value: '387', provinceId: '38', cap: 'Huyện' },
    { label: 'Lang Chánh', value: '388', provinceId: '38', cap: 'Huyện' },
    { label: 'Ngọc Lặc', value: '389', provinceId: '38', cap: 'Huyện' },
    { label: 'Cẩm Thủy', value: '390', provinceId: '38', cap: 'Huyện' },
    { label: 'Thạch Thành', value: '391', provinceId: '38', cap: 'Huyện' },
    { label: 'Hà Trung', value: '392', provinceId: '38', cap: 'Huyện' },
    { label: 'Vĩnh Lộc', value: '393', provinceId: '38', cap: 'Huyện' },
    { label: 'Yên Định', value: '394', provinceId: '38', cap: 'Huyện' },
    { label: 'Thọ Xuân', value: '395', provinceId: '38', cap: 'Huyện' },
    { label: 'Thường Xuân', value: '396', provinceId: '38', cap: 'Huyện' },
    { label: 'Triệu Sơn', value: '397', provinceId: '38', cap: 'Huyện' },
    { label: 'Thiệu Hóa', value: '398', provinceId: '38', cap: 'Huyện' },
    { label: 'Hoằng Hóa', value: '399', provinceId: '38', cap: 'Huyện' },
    { label: 'Hậu Lộc', value: '400', provinceId: '38', cap: 'Huyện' },
    { label: 'Nga Sơn', value: '401', provinceId: '38', cap: 'Huyện' },
    { label: 'Như Xuân', value: '402', provinceId: '38', cap: 'Huyện' },
    { label: 'Như Thanh', value: '403', provinceId: '38', cap: 'Huyện' },
    { label: 'Nông Cống', value: '404', provinceId: '38', cap: 'Huyện' },
    { label: 'Đông Sơn', value: '405', provinceId: '38', cap: 'Huyện' },
    { label: 'Quảng Xương', value: '406', provinceId: '38', cap: 'Huyện' },
    { label: 'Nghi Sơn', value: '407', provinceId: '38', cap: 'Thị xã' },
    { label: 'Vinh', value: '412', provinceId: '40', cap: 'Thành phố' },
    { label: 'Cửa Lò', value: '413', provinceId: '40', cap: 'Thị xã' },
    { label: 'Thái Hoà', value: '414', provinceId: '40', cap: 'Thị xã' },
    { label: 'Quế Phong', value: '415', provinceId: '40', cap: 'Huyện' },
    { label: 'Quỳ Châu', value: '416', provinceId: '40', cap: 'Huyện' },
    { label: 'Kỳ Sơn', value: '417', provinceId: '40', cap: 'Huyện' },
    { label: 'Tương Dương', value: '418', provinceId: '40', cap: 'Huyện' },
    { label: 'Nghĩa Đàn', value: '419', provinceId: '40', cap: 'Huyện' },
    { label: 'Quỳ Hợp', value: '420', provinceId: '40', cap: 'Huyện' },
    { label: 'Quỳnh Lưu', value: '421', provinceId: '40', cap: 'Huyện' },
    { label: 'Con Cuông', value: '422', provinceId: '40', cap: 'Huyện' },
    { label: 'Tân Kỳ', value: '423', provinceId: '40', cap: 'Huyện' },
    { label: 'Anh Sơn', value: '424', provinceId: '40', cap: 'Huyện' },
    { label: 'Diễn Châu', value: '425', provinceId: '40', cap: 'Huyện' },
    { label: 'Yên Thành', value: '426', provinceId: '40', cap: 'Huyện' },
    { label: 'Đô Lương', value: '427', provinceId: '40', cap: 'Huyện' },
    { label: 'Thanh Chương', value: '428', provinceId: '40', cap: 'Huyện' },
    { label: 'Nghi Lộc', value: '429', provinceId: '40', cap: 'Huyện' },
    { label: 'Nam Đàn', value: '430', provinceId: '40', cap: 'Huyện' },
    { label: 'Hưng Nguyên', value: '431', provinceId: '40', cap: 'Huyện' },
    { label: 'Hoàng Mai', value: '432', provinceId: '40', cap: 'Thị xã' },
    { label: 'Hà Tĩnh', value: '436', provinceId: '42', cap: 'Thành phố' },
    { label: 'Hồng Lĩnh', value: '437', provinceId: '42', cap: 'Thị xã' },
    { label: 'Hương Sơn', value: '439', provinceId: '42', cap: 'Huyện' },
    { label: 'Đức Thọ', value: '440', provinceId: '42', cap: 'Huyện' },
    { label: 'Vũ Quang', value: '441', provinceId: '42', cap: 'Huyện' },
    { label: 'Nghi Xuân', value: '442', provinceId: '42', cap: 'Huyện' },
    { label: 'Can Lộc', value: '443', provinceId: '42', cap: 'Huyện' },
    { label: 'Hương Khê', value: '444', provinceId: '42', cap: 'Huyện' },
    { label: 'Thạch Hà', value: '445', provinceId: '42', cap: 'Huyện' },
    { label: 'Cẩm Xuyên', value: '446', provinceId: '42', cap: 'Huyện' },
    { label: 'Kỳ Anh', value: '447', provinceId: '42', cap: 'Huyện' },
    { label: 'Lộc Hà', value: '448', provinceId: '42', cap: 'Huyện' },
    { label: 'Kỳ Anh', value: '449', provinceId: '42', cap: 'Thị xã' },
    { label: 'Đồng Hới', value: '450', provinceId: '44', cap: 'Thành phố' },
    { label: 'Minh Hóa', value: '452', provinceId: '44', cap: 'Huyện' },
    { label: 'Tuyên Hóa', value: '453', provinceId: '44', cap: 'Huyện' },
    { label: 'Quảng Trạch', value: '454', provinceId: '44', cap: 'Huyện' },
    { label: 'Bố Trạch', value: '455', provinceId: '44', cap: 'Huyện' },
    { label: 'Quảng Ninh', value: '456', provinceId: '44', cap: 'Huyện' },
    { label: 'Lệ Thủy', value: '457', provinceId: '44', cap: 'Huyện' },
    { label: 'Ba Đồn', value: '458', provinceId: '44', cap: 'Thị xã' },
    { label: 'Đông Hà', value: '461', provinceId: '45', cap: 'Thành phố' },
    { label: 'Quảng Trị', value: '462', provinceId: '45', cap: 'Thị xã' },
    { label: 'Vĩnh Linh', value: '464', provinceId: '45', cap: 'Huyện' },
    { label: 'Hướng Hóa', value: '465', provinceId: '45', cap: 'Huyện' },
    { label: 'Gio Linh', value: '466', provinceId: '45', cap: 'Huyện' },
    { label: 'Đa Krông', value: '467', provinceId: '45', cap: 'Huyện' },
    { label: 'Cam Lộ', value: '468', provinceId: '45', cap: 'Huyện' },
    { label: 'Triệu Phong', value: '469', provinceId: '45', cap: 'Huyện' },
    { label: 'Hải Lăng', value: '470', provinceId: '45', cap: 'Huyện' },
    { label: 'Cồn Cỏ', value: '471', provinceId: '45', cap: 'Huyện' },
    { label: 'Huế', value: '474', provinceId: '46', cap: 'Thành phố' },
    { label: 'Phong Điền', value: '476', provinceId: '46', cap: 'Huyện' },
    { label: 'Quảng Điền', value: '477', provinceId: '46', cap: 'Huyện' },
    { label: 'Phú Vang', value: '478', provinceId: '46', cap: 'Huyện' },
    { label: 'Hương Thủy', value: '479', provinceId: '46', cap: 'Thị xã' },
    { label: 'Hương Trà', value: '480', provinceId: '46', cap: 'Thị xã' },
    { label: 'A Lưới', value: '481', provinceId: '46', cap: 'Huyện' },
    { label: 'Phú Lộc', value: '482', provinceId: '46', cap: 'Huyện' },
    { label: 'Nam Đông', value: '483', provinceId: '46', cap: 'Huyện' },
    { label: 'Liên Chiểu', value: '490', provinceId: '48', cap: 'Quận' },
    { label: 'Thanh Khê', value: '491', provinceId: '48', cap: 'Quận' },
    { label: 'Hải Châu', value: '492', provinceId: '48', cap: 'Quận' },
    { label: 'Sơn Trà', value: '493', provinceId: '48', cap: 'Quận' },
    { label: 'Ngũ Hành Sơn', value: '494', provinceId: '48', cap: 'Quận' },
    { label: 'Cẩm Lệ', value: '495', provinceId: '48', cap: 'Quận' },
    { label: 'Hòa Vang', value: '497', provinceId: '48', cap: 'Huyện' },
    { label: 'Hoàng Sa', value: '498', provinceId: '48', cap: 'Huyện' },
    { label: 'Tam Kỳ', value: '502', provinceId: '49', cap: 'Thành phố' },
    { label: 'Hội An', value: '503', provinceId: '49', cap: 'Thành phố' },
    { label: 'Tây Giang', value: '504', provinceId: '49', cap: 'Huyện' },
    { label: 'Đông Giang', value: '505', provinceId: '49', cap: 'Huyện' },
    { label: 'Đại Lộc', value: '506', provinceId: '49', cap: 'Huyện' },
    { label: 'Điện Bàn', value: '507', provinceId: '49', cap: 'Thị xã' },
    { label: 'Duy Xuyên', value: '508', provinceId: '49', cap: 'Huyện' },
    { label: 'Quế Sơn', value: '509', provinceId: '49', cap: 'Huyện' },
    { label: 'Nam Giang', value: '510', provinceId: '49', cap: 'Huyện' },
    { label: 'Phước Sơn', value: '511', provinceId: '49', cap: 'Huyện' },
    { label: 'Hiệp Đức', value: '512', provinceId: '49', cap: 'Huyện' },
    { label: 'Thăng Bình', value: '513', provinceId: '49', cap: 'Huyện' },
    { label: 'Tiên Phước', value: '514', provinceId: '49', cap: 'Huyện' },
    { label: 'Bắc Trà My', value: '515', provinceId: '49', cap: 'Huyện' },
    { label: 'Nam Trà My', value: '516', provinceId: '49', cap: 'Huyện' },
    { label: 'Núi Thành', value: '517', provinceId: '49', cap: 'Huyện' },
    { label: 'Phú Ninh', value: '518', provinceId: '49', cap: 'Huyện' },
    { label: 'Nông Sơn', value: '519', provinceId: '49', cap: 'Huyện' },
    { label: 'Quảng Ngãi', value: '522', provinceId: '51', cap: 'Thành phố' },
    { label: 'Bình Sơn', value: '524', provinceId: '51', cap: 'Huyện' },
    { label: 'Trà Bồng', value: '525', provinceId: '51', cap: 'Huyện' },
    { label: 'Sơn Tịnh', value: '527', provinceId: '51', cap: 'Huyện' },
    { label: 'Tư Nghĩa', value: '528', provinceId: '51', cap: 'Huyện' },
    { label: 'Sơn Hà', value: '529', provinceId: '51', cap: 'Huyện' },
    { label: 'Sơn Tây', value: '530', provinceId: '51', cap: 'Huyện' },
    { label: 'Minh Long', value: '531', provinceId: '51', cap: 'Huyện' },
    { label: 'Nghĩa Hành', value: '532', provinceId: '51', cap: 'Huyện' },
    { label: 'Mộ Đức', value: '533', provinceId: '51', cap: 'Huyện' },
    { label: 'Đức Phổ', value: '534', provinceId: '51', cap: 'Thị xã' },
    { label: 'Ba Tơ', value: '535', provinceId: '51', cap: 'Huyện' },
    { label: 'Lý Sơn', value: '536', provinceId: '51', cap: 'Huyện' },
    { label: 'Quy Nhơn', value: '540', provinceId: '52', cap: 'Thành phố' },
    { label: 'An Lão', value: '542', provinceId: '52', cap: 'Huyện' },
    { label: 'Hoài Nhơn', value: '543', provinceId: '52', cap: 'Thị xã' },
    { label: 'Hoài Ân', value: '544', provinceId: '52', cap: 'Huyện' },
    { label: 'Phù Mỹ', value: '545', provinceId: '52', cap: 'Huyện' },
    { label: 'Vĩnh Thạnh', value: '546', provinceId: '52', cap: 'Huyện' },
    { label: 'Tây Sơn', value: '547', provinceId: '52', cap: 'Huyện' },
    { label: 'Phù Cát', value: '548', provinceId: '52', cap: 'Huyện' },
    { label: 'An Nhơn', value: '549', provinceId: '52', cap: 'Thị xã' },
    { label: 'Tuy Phước', value: '550', provinceId: '52', cap: 'Huyện' },
    { label: 'Vân Canh', value: '551', provinceId: '52', cap: 'Huyện' },
    { label: 'Tuy Hoà', value: '555', provinceId: '54', cap: 'Thành phố' },
    { label: 'Sông Cầu', value: '557', provinceId: '54', cap: 'Thị xã' },
    { label: 'Đồng Xuân', value: '558', provinceId: '54', cap: 'Huyện' },
    { label: 'Tuy An', value: '559', provinceId: '54', cap: 'Huyện' },
    { label: 'Sơn Hòa', value: '560', provinceId: '54', cap: 'Huyện' },
    { label: 'Sông Hinh', value: '561', provinceId: '54', cap: 'Huyện' },
    { label: 'Tây Hoà', value: '562', provinceId: '54', cap: 'Huyện' },
    { label: 'Phú Hoà', value: '563', provinceId: '54', cap: 'Huyện' },
    { label: 'Đông Hòa', value: '564', provinceId: '54', cap: 'Thị xã' },
    { label: 'Nha Trang', value: '568', provinceId: '56', cap: 'Thành phố' },
    { label: 'Cam Ranh', value: '569', provinceId: '56', cap: 'Thành phố' },
    { label: 'Cam Lâm', value: '570', provinceId: '56', cap: 'Huyện' },
    { label: 'Vạn Ninh', value: '571', provinceId: '56', cap: 'Huyện' },
    { label: 'Ninh Hòa', value: '572', provinceId: '56', cap: 'Thị xã' },
    { label: 'Khánh Vĩnh', value: '573', provinceId: '56', cap: 'Huyện' },
    { label: 'Diên Khánh', value: '574', provinceId: '56', cap: 'Huyện' },
    { label: 'Khánh Sơn', value: '575', provinceId: '56', cap: 'Huyện' },
    { label: 'Trường Sa', value: '576', provinceId: '56', cap: 'Huyện' },
    { label: 'Phan Rang-Tháp Chàm', value: '582', provinceId: '58', cap: 'Thành phố' },
    { label: 'Bác Ái', value: '584', provinceId: '58', cap: 'Huyện' },
    { label: 'Ninh Sơn', value: '585', provinceId: '58', cap: 'Huyện' },
    { label: 'Ninh Hải', value: '586', provinceId: '58', cap: 'Huyện' },
    { label: 'Ninh Phước', value: '587', provinceId: '58', cap: 'Huyện' },
    { label: 'Thuận Bắc', value: '588', provinceId: '58', cap: 'Huyện' },
    { label: 'Thuận Nam', value: '589', provinceId: '58', cap: 'Huyện' },
    { label: 'Phan Thiết', value: '593', provinceId: '60', cap: 'Thành phố' },
    { label: 'La Gi', value: '594', provinceId: '60', cap: 'Thị xã' },
    { label: 'Tuy Phong', value: '595', provinceId: '60', cap: 'Huyện' },
    { label: 'Bắc Bình', value: '596', provinceId: '60', cap: 'Huyện' },
    { label: 'Hàm Thuận Bắc', value: '597', provinceId: '60', cap: 'Huyện' },
    { label: 'Hàm Thuận Nam', value: '598', provinceId: '60', cap: 'Huyện' },
    { label: 'Tánh Linh', value: '599', provinceId: '60', cap: 'Huyện' },
    { label: 'Đức Linh', value: '600', provinceId: '60', cap: 'Huyện' },
    { label: 'Hàm Tân', value: '601', provinceId: '60', cap: 'Huyện' },
    { label: 'Phú Quí', value: '602', provinceId: '60', cap: 'Huyện' },
    { label: 'Kon Tum', value: '608', provinceId: '62', cap: 'Thành phố' },
    { label: 'Đắk Glei', value: '610', provinceId: '62', cap: 'Huyện' },
    { label: 'Ngọc Hồi', value: '611', provinceId: '62', cap: 'Huyện' },
    { label: 'Đắk Tô', value: '612', provinceId: '62', cap: 'Huyện' },
    { label: 'Kon Plông', value: '613', provinceId: '62', cap: 'Huyện' },
    { label: 'Kon Rẫy', value: '614', provinceId: '62', cap: 'Huyện' },
    { label: 'Đắk Hà', value: '615', provinceId: '62', cap: 'Huyện' },
    { label: 'Sa Thầy', value: '616', provinceId: '62', cap: 'Huyện' },
    { label: 'Tu Mơ Rông', value: '617', provinceId: '62', cap: 'Huyện' },
    { label: "Ia H' Drai", value: '618', provinceId: '62', cap: 'Huyện' },
    { label: 'Pleiku', value: '622', provinceId: '64', cap: 'Thành phố' },
    { label: 'An Khê', value: '623', provinceId: '64', cap: 'Thị xã' },
    { label: 'Ayun Pa', value: '624', provinceId: '64', cap: 'Thị xã' },
    { label: 'KBang', value: '625', provinceId: '64', cap: 'Huyện' },
    { label: 'Đăk Đoa', value: '626', provinceId: '64', cap: 'Huyện' },
    { label: 'Chư Păh', value: '627', provinceId: '64', cap: 'Huyện' },
    { label: 'Ia Grai', value: '628', provinceId: '64', cap: 'Huyện' },
    { label: 'Mang Yang', value: '629', provinceId: '64', cap: 'Huyện' },
    { label: 'Kông Chro', value: '630', provinceId: '64', cap: 'Huyện' },
    { label: 'Đức Cơ', value: '631', provinceId: '64', cap: 'Huyện' },
    { label: 'Chư Prông', value: '632', provinceId: '64', cap: 'Huyện' },
    { label: 'Chư Sê', value: '633', provinceId: '64', cap: 'Huyện' },
    { label: 'Đăk Pơ', value: '634', provinceId: '64', cap: 'Huyện' },
    { label: 'Ia Pa', value: '635', provinceId: '64', cap: 'Huyện' },
    { label: 'Krông Pa', value: '637', provinceId: '64', cap: 'Huyện' },
    { label: 'Phú Thiện', value: '638', provinceId: '64', cap: 'Huyện' },
    { label: 'Chư Pưh', value: '639', provinceId: '64', cap: 'Huyện' },
    { label: 'Buôn Ma Thuột', value: '643', provinceId: '66', cap: 'Thành phố' },
    { label: 'Buôn Hồ', value: '644', provinceId: '66', cap: 'Thị xã' },
    { label: "Ea H'leo", value: '645', provinceId: '66', cap: 'Huyện' },
    { label: 'Ea Súp', value: '646', provinceId: '66', cap: 'Huyện' },
    { label: 'Buôn Đôn', value: '647', provinceId: '66', cap: 'Huyện' },
    { label: "Cư M'gar", value: '648', provinceId: '66', cap: 'Huyện' },
    { label: 'Krông Búk', value: '649', provinceId: '66', cap: 'Huyện' },
    { label: 'Krông Năng', value: '650', provinceId: '66', cap: 'Huyện' },
    { label: 'Ea Kar', value: '651', provinceId: '66', cap: 'Huyện' },
    { label: "M'Đrắk", value: '652', provinceId: '66', cap: 'Huyện' },
    { label: 'Krông Bông', value: '653', provinceId: '66', cap: 'Huyện' },
    { label: 'Krông Pắc', value: '654', provinceId: '66', cap: 'Huyện' },
    { label: 'Krông A Na', value: '655', provinceId: '66', cap: 'Huyện' },
    { label: 'Lắk', value: '656', provinceId: '66', cap: 'Huyện' },
    { label: 'Cư Kuin', value: '657', provinceId: '66', cap: 'Huyện' },
    { label: 'Gia Nghĩa', value: '660', provinceId: '67', cap: 'Thành phố' },
    { label: 'Đăk Glong', value: '661', provinceId: '67', cap: 'Huyện' },
    { label: 'Cư Jút', value: '662', provinceId: '67', cap: 'Huyện' },
    { label: 'Đắk Mil', value: '663', provinceId: '67', cap: 'Huyện' },
    { label: 'Krông Nô', value: '664', provinceId: '67', cap: 'Huyện' },
    { label: 'Đắk Song', value: '665', provinceId: '67', cap: 'Huyện' },
    { label: "Đắk R'Lấp", value: '666', provinceId: '67', cap: 'Huyện' },
    { label: 'Tuy Đức', value: '667', provinceId: '67', cap: 'Huyện' },
    { label: 'Đà Lạt', value: '672', provinceId: '68', cap: 'Thành phố' },
    { label: 'Bảo Lộc', value: '673', provinceId: '68', cap: 'Thành phố' },
    { label: 'Đam Rông', value: '674', provinceId: '68', cap: 'Huyện' },
    { label: 'Lạc Dương', value: '675', provinceId: '68', cap: 'Huyện' },
    { label: 'Lâm Hà', value: '676', provinceId: '68', cap: 'Huyện' },
    { label: 'Đơn Dương', value: '677', provinceId: '68', cap: 'Huyện' },
    { label: 'Đức Trọng', value: '678', provinceId: '68', cap: 'Huyện' },
    { label: 'Di Linh', value: '679', provinceId: '68', cap: 'Huyện' },
    { label: 'Bảo Lâm', value: '680', provinceId: '68', cap: 'Huyện' },
    { label: 'Đạ Huoai', value: '681', provinceId: '68', cap: 'Huyện' },
    { label: 'Đạ Tẻh', value: '682', provinceId: '68', cap: 'Huyện' },
    { label: 'Cát Tiên', value: '683', provinceId: '68', cap: 'Huyện' },
    { label: 'Phước Long', value: '688', provinceId: '70', cap: 'Thị xã' },
    { label: 'Đồng Xoài', value: '689', provinceId: '70', cap: 'Thành phố' },
    { label: 'Bình Long', value: '690', provinceId: '70', cap: 'Thị xã' },
    { label: 'Bù Gia Mập', value: '691', provinceId: '70', cap: 'Huyện' },
    { label: 'Lộc Ninh', value: '692', provinceId: '70', cap: 'Huyện' },
    { label: 'Bù Đốp', value: '693', provinceId: '70', cap: 'Huyện' },
    { label: 'Hớn Quản', value: '694', provinceId: '70', cap: 'Huyện' },
    { label: 'Đồng Phú', value: '695', provinceId: '70', cap: 'Huyện' },
    { label: 'Bù Đăng', value: '696', provinceId: '70', cap: 'Huyện' },
    { label: 'Chơn Thành', value: '697', provinceId: '70', cap: 'Huyện' },
    { label: 'Phú Riềng', value: '698', provinceId: '70', cap: 'Huyện' },
    { label: 'Tây Ninh', value: '703', provinceId: '72', cap: 'Thành phố' },
    { label: 'Tân Biên', value: '705', provinceId: '72', cap: 'Huyện' },
    { label: 'Tân Châu', value: '706', provinceId: '72', cap: 'Huyện' },
    { label: 'Dương Minh Châu', value: '707', provinceId: '72', cap: 'Huyện' },
    { label: 'Châu Thành', value: '708', provinceId: '72', cap: 'Huyện' },
    { label: 'Hòa Thành', value: '709', provinceId: '72', cap: 'Thị xã' },
    { label: 'Gò Dầu', value: '710', provinceId: '72', cap: 'Huyện' },
    { label: 'Bến Cầu', value: '711', provinceId: '72', cap: 'Huyện' },
    { label: 'Trảng Bàng', value: '712', provinceId: '72', cap: 'Thị xã' },
    { label: 'Thủ Dầu Một', value: '718', provinceId: '74', cap: 'Thành phố' },
    { label: 'Bàu Bàng', value: '719', provinceId: '74', cap: 'Huyện' },
    { label: 'Dầu Tiếng', value: '720', provinceId: '74', cap: 'Huyện' },
    { label: 'Bến Cát', value: '721', provinceId: '74', cap: 'Thị xã' },
    { label: 'Phú Giáo', value: '722', provinceId: '74', cap: 'Huyện' },
    { label: 'Tân Uyên', value: '723', provinceId: '74', cap: 'Thị xã' },
    { label: 'Dĩ An', value: '724', provinceId: '74', cap: 'Thành phố' },
    { label: 'Thuận An', value: '725', provinceId: '74', cap: 'Thành phố' },
    { label: 'Bắc Tân Uyên', value: '726', provinceId: '74', cap: 'Huyện' },
    { label: 'Biên Hòa', value: '731', provinceId: '75', cap: 'Thành phố' },
    { label: 'Long Khánh', value: '732', provinceId: '75', cap: 'Thành phố' },
    { label: 'Tân Phú', value: '734', provinceId: '75', cap: 'Huyện' },
    { label: 'Vĩnh Cửu', value: '735', provinceId: '75', cap: 'Huyện' },
    { label: 'Định Quán', value: '736', provinceId: '75', cap: 'Huyện' },
    { label: 'Trảng Bom', value: '737', provinceId: '75', cap: 'Huyện' },
    { label: 'Thống Nhất', value: '738', provinceId: '75', cap: 'Huyện' },
    { label: 'Cẩm Mỹ', value: '739', provinceId: '75', cap: 'Huyện' },
    { label: 'Long Thành', value: '740', provinceId: '75', cap: 'Huyện' },
    { label: 'Xuân Lộc', value: '741', provinceId: '75', cap: 'Huyện' },
    { label: 'Nhơn Trạch', value: '742', provinceId: '75', cap: 'Huyện' },
    { label: 'Vũng Tàu', value: '747', provinceId: '77', cap: 'Thành phố' },
    { label: 'Bà Rịa', value: '748', provinceId: '77', cap: 'Thành phố' },
    { label: 'Châu Đức', value: '750', provinceId: '77', cap: 'Huyện' },
    { label: 'Xuyên Mộc', value: '751', provinceId: '77', cap: 'Huyện' },
    { label: 'Long Điền', value: '752', provinceId: '77', cap: 'Huyện' },
    { label: 'Đất Đỏ', value: '753', provinceId: '77', cap: 'Huyện' },
    { label: 'Phú Mỹ', value: '754', provinceId: '77', cap: 'Thị xã' },
    { label: 'Côn Đảo', value: '755', provinceId: '77', cap: 'Huyện' },
    { label: '1', value: '760', provinceId: '79', cap: 'Quận' },
    { label: '12', value: '761', provinceId: '79', cap: 'Quận' },
    { label: 'Thủ Đức', value: '762', provinceId: '79', cap: 'Quận' },
    { label: '9', value: '763', provinceId: '79', cap: 'Quận' },
    { label: 'Gò Vấp', value: '764', provinceId: '79', cap: 'Quận' },
    { label: 'Bình Thạnh', value: '765', provinceId: '79', cap: 'Quận' },
    { label: 'Tân Bình', value: '766', provinceId: '79', cap: 'Quận' },
    { label: 'Tân Phú', value: '767', provinceId: '79', cap: 'Quận' },
    { label: 'Phú Nhuận', value: '768', provinceId: '79', cap: 'Quận' },
    { label: '2', value: '769', provinceId: '79', cap: 'Quận' },
    { label: '3', value: '770', provinceId: '79', cap: 'Quận' },
    { label: '10', value: '771', provinceId: '79', cap: 'Quận' },
    { label: '11', value: '772', provinceId: '79', cap: 'Quận' },
    { label: '4', value: '773', provinceId: '79', cap: 'Quận' },
    { label: '5', value: '774', provinceId: '79', cap: 'Quận' },
    { label: '6', value: '775', provinceId: '79', cap: 'Quận' },
    { label: '8', value: '776', provinceId: '79', cap: 'Quận' },
    { label: 'Bình Tân', value: '777', provinceId: '79', cap: 'Quận' },
    { label: '7', value: '778', provinceId: '79', cap: 'Quận' },
    { label: 'Củ Chi', value: '783', provinceId: '79', cap: 'Huyện' },
    { label: 'Hóc Môn', value: '784', provinceId: '79', cap: 'Huyện' },
    { label: 'Bình Chánh', value: '785', provinceId: '79', cap: 'Huyện' },
    { label: 'Nhà Bè', value: '786', provinceId: '79', cap: 'Huyện' },
    { label: 'Cần Giờ', value: '787', provinceId: '79', cap: 'Huyện' },
    { label: 'Tân An', value: '794', provinceId: '80', cap: 'Thành phố' },
    { label: 'Kiến Tường', value: '795', provinceId: '80', cap: 'Thị xã' },
    { label: 'Tân Hưng', value: '796', provinceId: '80', cap: 'Huyện' },
    { label: 'Vĩnh Hưng', value: '797', provinceId: '80', cap: 'Huyện' },
    { label: 'Mộc Hóa', value: '798', provinceId: '80', cap: 'Huyện' },
    { label: 'Tân Thạnh', value: '799', provinceId: '80', cap: 'Huyện' },
    { label: 'Thạnh Hóa', value: '800', provinceId: '80', cap: 'Huyện' },
    { label: 'Đức Huệ', value: '801', provinceId: '80', cap: 'Huyện' },
    { label: 'Đức Hòa', value: '802', provinceId: '80', cap: 'Huyện' },
    { label: 'Bến Lức', value: '803', provinceId: '80', cap: 'Huyện' },
    { label: 'Thủ Thừa', value: '804', provinceId: '80', cap: 'Huyện' },
    { label: 'Tân Trụ', value: '805', provinceId: '80', cap: 'Huyện' },
    { label: 'Cần Đước', value: '806', provinceId: '80', cap: 'Huyện' },
    { label: 'Cần Giuộc', value: '807', provinceId: '80', cap: 'Huyện' },
    { label: 'Châu Thành', value: '808', provinceId: '80', cap: 'Huyện' },
    { label: 'Mỹ Tho', value: '815', provinceId: '82', cap: 'Thành phố' },
    { label: 'Gò Công', value: '816', provinceId: '82', cap: 'Thị xã' },
    { label: 'Cai Lậy', value: '817', provinceId: '82', cap: 'Thị xã' },
    { label: 'Tân Phước', value: '818', provinceId: '82', cap: 'Huyện' },
    { label: 'Cái Bè', value: '819', provinceId: '82', cap: 'Huyện' },
    { label: 'Cai Lậy', value: '820', provinceId: '82', cap: 'Huyện' },
    { label: 'Châu Thành', value: '821', provinceId: '82', cap: 'Huyện' },
    { label: 'Chợ Gạo', value: '822', provinceId: '82', cap: 'Huyện' },
    { label: 'Gò Công Tây', value: '823', provinceId: '82', cap: 'Huyện' },
    { label: 'Gò Công Đông', value: '824', provinceId: '82', cap: 'Huyện' },
    { label: 'Tân Phú Đông', value: '825', provinceId: '82', cap: 'Huyện' },
    { label: 'Bến Tre', value: '829', provinceId: '83', cap: 'Thành phố' },
    { label: 'Châu Thành', value: '831', provinceId: '83', cap: 'Huyện' },
    { label: 'Chợ Lách', value: '832', provinceId: '83', cap: 'Huyện' },
    { label: 'Mỏ Cày Nam', value: '833', provinceId: '83', cap: 'Huyện' },
    { label: 'Giồng Trôm', value: '834', provinceId: '83', cap: 'Huyện' },
    { label: 'Bình Đại', value: '835', provinceId: '83', cap: 'Huyện' },
    { label: 'Ba Tri', value: '836', provinceId: '83', cap: 'Huyện' },
    { label: 'Thạnh Phú', value: '837', provinceId: '83', cap: 'Huyện' },
    { label: 'Mỏ Cày Bắc', value: '838', provinceId: '83', cap: 'Huyện' },
    { label: 'Trà Vinh', value: '842', provinceId: '84', cap: 'Thành phố' },
    { label: 'Càng Long', value: '844', provinceId: '84', cap: 'Huyện' },
    { label: 'Cầu Kè', value: '845', provinceId: '84', cap: 'Huyện' },
    { label: 'Tiểu Cần', value: '846', provinceId: '84', cap: 'Huyện' },
    { label: 'Châu Thành', value: '847', provinceId: '84', cap: 'Huyện' },
    { label: 'Cầu Ngang', value: '848', provinceId: '84', cap: 'Huyện' },
    { label: 'Trà Cú', value: '849', provinceId: '84', cap: 'Huyện' },
    { label: 'Duyên Hải', value: '850', provinceId: '84', cap: 'Huyện' },
    { label: 'Duyên Hải', value: '851', provinceId: '84', cap: 'Thị xã' },
    { label: 'Vĩnh Long', value: '855', provinceId: '86', cap: 'Thành phố' },
    { label: 'Long Hồ', value: '857', provinceId: '86', cap: 'Huyện' },
    { label: 'Mang Thít', value: '858', provinceId: '86', cap: 'Huyện' },
    { label: 'Vũng Liêm', value: '859', provinceId: '86', cap: 'Huyện' },
    { label: 'Tam Bình', value: '860', provinceId: '86', cap: 'Huyện' },
    { label: 'Bình Minh', value: '861', provinceId: '86', cap: 'Thị xã' },
    { label: 'Trà Ôn', value: '862', provinceId: '86', cap: 'Huyện' },
    { label: 'Bình Tân', value: '863', provinceId: '86', cap: 'Huyện' },
    { label: 'Cao Lãnh', value: '866', provinceId: '87', cap: 'Thành phố' },
    { label: 'Sa Đéc', value: '867', provinceId: '87', cap: 'Thành phố' },
    { label: 'Hồng Ngự', value: '868', provinceId: '87', cap: 'Thành phố' },
    { label: 'Tân Hồng', value: '869', provinceId: '87', cap: 'Huyện' },
    { label: 'Hồng Ngự', value: '870', provinceId: '87', cap: 'Huyện' },
    { label: 'Tam Nông', value: '871', provinceId: '87', cap: 'Huyện' },
    { label: 'Tháp Mười', value: '872', provinceId: '87', cap: 'Huyện' },
    { label: 'Cao Lãnh', value: '873', provinceId: '87', cap: 'Huyện' },
    { label: 'Thanh Bình', value: '874', provinceId: '87', cap: 'Huyện' },
    { label: 'Lấp Vò', value: '875', provinceId: '87', cap: 'Huyện' },
    { label: 'Lai Vung', value: '876', provinceId: '87', cap: 'Huyện' },
    { label: 'Châu Thành', value: '877', provinceId: '87', cap: 'Huyện' },
    { label: 'Long Xuyên', value: '883', provinceId: '89', cap: 'Thành phố' },
    { label: 'Châu Đốc', value: '884', provinceId: '89', cap: 'Thành phố' },
    { label: 'An Phú', value: '886', provinceId: '89', cap: 'Huyện' },
    { label: 'Tân Châu', value: '887', provinceId: '89', cap: 'Thị xã' },
    { label: 'Phú Tân', value: '888', provinceId: '89', cap: 'Huyện' },
    { label: 'Châu Phú', value: '889', provinceId: '89', cap: 'Huyện' },
    { label: 'Tịnh Biên', value: '890', provinceId: '89', cap: 'Huyện' },
    { label: 'Tri Tôn', value: '891', provinceId: '89', cap: 'Huyện' },
    { label: 'Châu Thành', value: '892', provinceId: '89', cap: 'Huyện' },
    { label: 'Chợ Mới', value: '893', provinceId: '89', cap: 'Huyện' },
    { label: 'Thoại Sơn', value: '894', provinceId: '89', cap: 'Huyện' },
    { label: 'Rạch Giá', value: '899', provinceId: '91', cap: 'Thành phố' },
    { label: 'Hà Tiên', value: '900', provinceId: '91', cap: 'Thành phố' },
    { label: 'Kiên Lương', value: '902', provinceId: '91', cap: 'Huyện' },
    { label: 'Hòn Đất', value: '903', provinceId: '91', cap: 'Huyện' },
    { label: 'Tân Hiệp', value: '904', provinceId: '91', cap: 'Huyện' },
    { label: 'Châu Thành', value: '905', provinceId: '91', cap: 'Huyện' },
    { label: 'Giồng Riềng', value: '906', provinceId: '91', cap: 'Huyện' },
    { label: 'Gò Quao', value: '907', provinceId: '91', cap: 'Huyện' },
    { label: 'An Biên', value: '908', provinceId: '91', cap: 'Huyện' },
    { label: 'An Minh', value: '909', provinceId: '91', cap: 'Huyện' },
    { label: 'Vĩnh Thuận', value: '910', provinceId: '91', cap: 'Huyện' },
    { label: 'Phú Quốc', value: '911', provinceId: '91', cap: 'Huyện' },
    { label: 'Kiên Hải', value: '912', provinceId: '91', cap: 'Huyện' },
    { label: 'U Minh Thượng', value: '913', provinceId: '91', cap: 'Huyện' },
    { label: 'Giang Thành', value: '914', provinceId: '91', cap: 'Huyện' },
    { label: 'Ninh Kiều', value: '916', provinceId: '92', cap: 'Quận' },
    { label: 'Ô Môn', value: '917', provinceId: '92', cap: 'Quận' },
    { label: 'Bình Thuỷ', value: '918', provinceId: '92', cap: 'Quận' },
    { label: 'Cái Răng', value: '919', provinceId: '92', cap: 'Quận' },
    { label: 'Thốt Nốt', value: '923', provinceId: '92', cap: 'Quận' },
    { label: 'Vĩnh Thạnh', value: '924', provinceId: '92', cap: 'Huyện' },
    { label: 'Cờ Đỏ', value: '925', provinceId: '92', cap: 'Huyện' },
    { label: 'Phong Điền', value: '926', provinceId: '92', cap: 'Huyện' },
    { label: 'Thới Lai', value: '927', provinceId: '92', cap: 'Huyện' },
    { label: 'Vị Thanh', value: '930', provinceId: '93', cap: 'Thành phố' },
    { label: 'Ngã Bảy', value: '931', provinceId: '93', cap: 'Thành phố' },
    { label: 'Châu Thành A', value: '932', provinceId: '93', cap: 'Huyện' },
    { label: 'Châu Thành', value: '933', provinceId: '93', cap: 'Huyện' },
    { label: 'Phụng Hiệp', value: '934', provinceId: '93', cap: 'Huyện' },
    { label: 'Vị Thuỷ', value: '935', provinceId: '93', cap: 'Huyện' },
    { label: 'Long Mỹ', value: '936', provinceId: '93', cap: 'Huyện' },
    { label: 'Long Mỹ', value: '937', provinceId: '93', cap: 'Thị xã' },
    { label: 'Sóc Trăng', value: '941', provinceId: '94', cap: 'Thành phố' },
    { label: 'Châu Thành', value: '942', provinceId: '94', cap: 'Huyện' },
    { label: 'Kế Sách', value: '943', provinceId: '94', cap: 'Huyện' },
    { label: 'Mỹ Tú', value: '944', provinceId: '94', cap: 'Huyện' },
    { label: 'Cù Lao Dung', value: '945', provinceId: '94', cap: 'Huyện' },
    { label: 'Long Phú', value: '946', provinceId: '94', cap: 'Huyện' },
    { label: 'Mỹ Xuyên', value: '947', provinceId: '94', cap: 'Huyện' },
    { label: 'Ngã Năm', value: '948', provinceId: '94', cap: 'Thị xã' },
    { label: 'Thạnh Trị', value: '949', provinceId: '94', cap: 'Huyện' },
    { label: 'Vĩnh Châu', value: '950', provinceId: '94', cap: 'Thị xã' },
    { label: 'Trần Đề', value: '951', provinceId: '94', cap: 'Huyện' },
    { label: 'Bạc Liêu', value: '954', provinceId: '95', cap: 'Thành phố' },
    { label: 'Hồng Dân', value: '956', provinceId: '95', cap: 'Huyện' },
    { label: 'Phước Long', value: '957', provinceId: '95', cap: 'Huyện' },
    { label: 'Vĩnh Lợi', value: '958', provinceId: '95', cap: 'Huyện' },
    { label: 'Giá Rai', value: '959', provinceId: '95', cap: 'Thị xã' },
    { label: 'Đông Hải', value: '960', provinceId: '95', cap: 'Huyện' },
    { label: 'Hoà Bình', value: '961', provinceId: '95', cap: 'Huyện' },
    { label: 'Cà Mau', value: '964', provinceId: '96', cap: 'Thành phố' },
    { label: 'U Minh', value: '966', provinceId: '96', cap: 'Huyện' },
    { label: 'Thới Bình', value: '967', provinceId: '96', cap: 'Huyện' },
    { label: 'Trần Văn Thời', value: '968', provinceId: '96', cap: 'Huyện' },
    { label: 'Cái Nước', value: '969', provinceId: '96', cap: 'Huyện' },
    { label: 'Đầm Dơi', value: '970', provinceId: '96', cap: 'Huyện' },
    { label: 'Năm Căn', value: '971', provinceId: '96', cap: 'Huyện' },
    { label: 'Phú Tân', value: '972', provinceId: '96', cap: 'Huyện' },
    { label: 'Ngọc Hiển', value: '973', provinceId: '96', cap: 'Huyện' },
  ];