export const PROVINCE = [
    { label: 'Hà Nội', value: '01', cap: 'Thành phố' },
    { label: 'Hà Giang', value: '02', cap: 'Tỉnh' },
    { label: 'Cao Bằng', value: '04', cap: 'Tỉnh' },
    { label: 'Bắc Kạn', value: '06', cap: 'Tỉnh' },
    { label: 'Tuyên Quang', value: '08', cap: 'Tỉnh' },
    { label: 'Lào Cai', value: '10', cap: 'Tỉnh' },
    { label: 'Điện Biên', value: '11', cap: 'Tỉnh' },
    { label: 'Lai Châu', value: '12', cap: 'Tỉnh' },
    { label: 'Sơn La', value: '14', cap: 'Tỉnh' },
    { label: 'Yên Bái', value: '15', cap: 'Tỉnh' },
    { label: 'Hoà Bình', value: '17', cap: 'Tỉnh' },
    { label: 'Thái Nguyên', value: '19', cap: 'Tỉnh' },
    { label: 'Lạng Sơn', value: '20', cap: 'Tỉnh' },
    { label: 'Quảng Ninh', value: '22', cap: 'Tỉnh' },
    { label: 'Bắc Giang', value: '24', cap: 'Tỉnh' },
    { label: 'Phú Thọ', value: '25', cap: 'Tỉnh' },
    { label: 'Vĩnh Phúc', value: '26', cap: 'Tỉnh' },
    { label: 'Bắc Ninh', value: '27', cap: 'Tỉnh' },
    { label: 'Hải Dương', value: '30', cap: 'Tỉnh' },
    { label: 'Hải Phòng', value: '31', cap: 'Thành phố' },
    { label: 'Hưng Yên', value: '33', cap: 'Tỉnh' },
    { label: 'Thái Bình', value: '34', cap: 'Tỉnh' },
    { label: 'Hà Nam', value: '35', cap: 'Tỉnh' },
    { label: 'Nam Định', value: '36', cap: 'Tỉnh' },
    { label: 'Ninh Bình', value: '37', cap: 'Tỉnh' },
    { label: 'Thanh Hóa', value: '38', cap: 'Tỉnh' },
    { label: 'Nghệ An', value: '40', cap: 'Tỉnh' },
    { label: 'Hà Tĩnh', value: '42', cap: 'Tỉnh' },
    { label: 'Quảng Bình', value: '44', cap: 'Tỉnh' },
    { label: 'Quảng Trị', value: '45', cap: 'Tỉnh' },
    { label: 'Thừa Thiên Huế', value: '46', cap: 'Tỉnh' },
    { label: 'Đà Nẵng', value: '48', cap: 'Thành phố' },
    { label: 'Quảng Nam', value: '49', cap: 'Tỉnh' },
    { label: 'Quảng Ngãi', value: '51', cap: 'Tỉnh' },
    { label: 'Bình Định', value: '52', cap: 'Tỉnh' },
    { label: 'Phú Yên', value: '54', cap: 'Tỉnh' },
    { label: 'Khánh Hòa', value: '56', cap: 'Tỉnh' },
    { label: 'Ninh Thuận', value: '58', cap: 'Tỉnh' },
    { label: 'Bình Thuận', value: '60', cap: 'Tỉnh' },
    { label: 'Kon Tum', value: '62', cap: 'Tỉnh' },
    { label: 'Gia Lai', value: '64', cap: 'Tỉnh' },
    { label: 'Đắk Lắk', value: '66', cap: 'Tỉnh' },
    { label: 'Đắk Nông', value: '67', cap: 'Tỉnh' },
    { label: 'Lâm Đồng', value: '68', cap: 'Tỉnh' },
    { label: 'Bình Phước', value: '70', cap: 'Tỉnh' },
    { label: 'Tây Ninh', value: '72', cap: 'Tỉnh' },
    { label: 'Bình Dương', value: '74', cap: 'Tỉnh' },
    { label: 'Đồng Nai', value: '75', cap: 'Tỉnh' },
    { label: 'Bà Rịa - Vũng Tàu', value: '77', cap: 'Tỉnh' },
    { label: 'Hồ Chí Minh', value: '79', cap: 'Thành phố' },
    { label: 'Long An', value: '80', cap: 'Tỉnh' },
    { label: 'Tiền Giang', value: '82', cap: 'Tỉnh' },
    { label: 'Bến Tre', value: '83', cap: 'Tỉnh' },
    { label: 'Trà Vinh', value: '84', cap: 'Tỉnh' },
    { label: 'Vĩnh Long', value: '86', cap: 'Tỉnh' },
    { label: 'Đồng Tháp', value: '87', cap: 'Tỉnh' },
    { label: 'An Giang', value: '89', cap: 'Tỉnh' },
    { label: 'Kiên Giang', value: '91', cap: 'Tỉnh' },
    { label: 'Cần Thơ', value: '92', cap: 'Thành phố' },
    { label: 'Hậu Giang', value: '93', cap: 'Tỉnh' },
    { label: 'Sóc Trăng', value: '94', cap: 'Tỉnh' },
    { label: 'Bạc Liêu', value: '95', cap: 'Tỉnh' },
    { label: 'Cà Mau', value: '96', cap: 'Tỉnh' },
  ];
  