// Enhanced classesData with review information
const classesData = [
  {
    id: "CS101-A1",
    name: "Introduction to Programming",
    semester: "Semester 1",
    students: 45,
    schedule: "Mon/Wed 10:00-11:30 AM",
    TA: "Sarah Johnson",
    credit: 3,
    startDate: "2024-08-15",
    dueDate: "2024-12-20",
    year: 2022,
    status: "In Progress",
    reviewsCompleted: 40,
    totalReviews: 50,
    averageRating: 4.2,
    reviews: [
      {
        studentId: "ST1001",
        studentName: "Alex Johnson",
        rating: 4.5,
        comment:
          "Excellent course material, very engaging professor. Would recommend to anyone starting out in programming.",
        date: "2024-10-15",
        helpful: 12,
      },
      {
        studentId: "ST1042",
        studentName: "Emily Chen",
        rating: 3.8,
        comment:
          "Good content but assignments can be challenging for beginners. Office hours were very helpful.",
        date: "2024-10-12",
        helpful: 8,
      },
      {
        studentId: "ST1105",
        studentName: "Marcus Wong",
        rating: 4.7,
        comment:
          "One of the best intro courses I've taken. Clear explanations and practical examples.",
        date: "2024-10-10",
        helpful: 15,
      },
    ],
  },
  {
    id: "CS201-B2",
    name: "Data Structures",
    //semester: "S1-2024-2025",
    semester:"Semester 2",
    students: 35,
    schedule: "Tue/Thu 2:00-3:30 PM",
    TA: "Michael Chen",
    credit: 4,
    startDate: "2024-08-15",
    dueDate: "2024-12-20",
    year: "2022",
    status: "In Progress",
    reviewsCompleted: 28,
    totalReviews: 35,
    averageRating: 4.0,
    reviews: [
      {
        studentId: "ST2011",
        studentName: "Sophia Kim",
        rating: 4.2,
        comment:
          "Challenging but rewarding course. The professor explains complex concepts clearly.",
        date: "2024-10-14",
        helpful: 9,
      },
      {
        studentId: "ST2053",
        studentName: "Jacob Martinez",
        rating: 3.5,
        comment:
          "Good course content, but the pace can be a bit fast. More practice problems would help.",
        date: "2024-10-11",
        helpful: 7,
      },
    ],
  },
  {
    id: "CS301-C3",
    name: "Advanced Algorithms",
    semester:"Semester 2",
    students: 25,
    schedule: "Fri 1:00-4:00 PM",
    TA: "David Kim",
    credit: 3,
    startDate: "2024-08-15",
    dueDate: "2024-12-20",
    status: "In Progress",
    year: "2022",
    reviewsCompleted: 18,
    totalReviews: 25,
    averageRating: 4.5,
    reviews: [
      {
        studentId: "ST3022",
        studentName: "Emma Rodriguez",
        rating: 4.8,
        comment:
          "Excellent advanced course. Professor has deep knowledge and provides great insights.",
        date: "2024-10-13",
        helpful: 11,
      },
    ],
  },
  {
    id: "CS220-D4",
    name: "Database Systems",
    semester:"Semester 1",
    students: 40,
    schedule: "Mon/Wed 2:00-3:30 PM",
    TA: "Jennifer Wong",
    credit: 3,
    startDate: "2024-08-15",
    dueDate: "2024-12-20",
    year: "2022",
    status: "In Progress",
    reviewsCompleted: 32,
    totalReviews: 40,
    averageRating: 3.9,
    reviews: [
      {
        studentId: "ST4005",
        studentName: "Tyler Smith",
        rating: 3.7,
        comment:
          "Solid introduction to databases, but labs could use more guidance.",
        date: "2024-10-12",
        helpful: 6,
      },
      {
        studentId: "ST4018",
        studentName: "Olivia Garcia",
        rating: 4.1,
        comment:
          "Well-structured course with practical examples. SQL assignments were particularly useful.",
        date: "2024-10-09",
        helpful: 10,
      },
    ],
  },
  {
    id: "CS350-E5",
    name: "Software Engineering",
    semester:"Semester 1",
    students: 30,
    schedule: "Tue/Thu 10:00-11:30 AM",
    TA: "Robert Garcia",
    credit: 4,
    startDate: "2024-08-15",
    dueDate: "2024-12-20",
    year: "2022",
    status: "In Progress",
    reviewsCompleted: 25,
    totalReviews: 30,
    averageRating: 4.3,
    reviews: [
      {
        studentId: "ST5002",
        studentName: "Aiden Johnson",
        rating: 4.5,
        comment:
          "Great course for learning software development processes. Team project was challenging but rewarding.",
        date: "2024-10-15",
        helpful: 13,
      },
    ],
  },
];

export default classesData;
