const notificationsData = [
  {
    id: 1,
    title: "New Course Available",
    content: "New course available: React Basics",
    courseName: "React Basics",
    courseId: "CS101",
    time: new Date("2025-04-06T09:30:00"),
    isRead: false,
  },
  {
    id: 2,
    title: "Tuition Fee Invoice",
    content: "Your tuition fee invoice is ready",
    courseName: null,
    courseId: null,
    time: new Date("2025-04-05T14:15:00"),
    isRead: true,
  },
  {
    id: 3,
    title: "Schedule Update",
    content: "Class schedule updated for Software Engineering",
    courseName: "Software Engineering",
    courseId: "CS301",
    time: new Date("2025-04-05T10:45:00"),
    isRead: false,
  },
  {
    id: 4,
    title: "Assignment Deadline",
    content: "Reminder: Assignment deadline tomorrow",
    courseName: "Data Structures",
    courseId: "CS201",
    time: new Date("2025-04-06T08:00:00"),
    isRead: true,
  },
  {
    id: 5,
    title: "New Course Available",
    content: "New course available: Advanced JavaScript",
    courseName: "Advanced JavaScript",
    courseId: "CS102",
    time: new Date("2025-04-04T11:20:00"),
    isRead: false,
  },
  {
    id: 6,
    title: "Scholarship Opportunity",
    content: "New scholarship opportunity available",
    courseName: null,
    courseId: null,
    time: new Date("2025-04-03T16:30:00"),
    isRead: true,
  },
  {
    id: 7,
    title: "Career Fair",
    content: "University Career Fair next week",
    courseName: null,
    courseId: null,
    time: new Date("2025-04-02T09:15:00"),
    isRead: false,
  },
  {
    id: 8,
    title: "Exam Schedule",
    content: "Final exam schedule posted",
    courseName: null,
    courseId: null,
    time: new Date("2025-04-01T13:45:00"),
    isRead: true,
  },
  {
    id: 9,
    title: "System Maintenance",
    content: "Student portal will be down for maintenance",
    courseName: null,
    courseId: null,
    time: new Date("2025-04-07T08:00:00"),
    isRead: false,
  },
  {
    id: 10,
    title: "New Grade Posted",
    content: "Your grade for Midterm Exam has been posted",
    courseName: "Data Structures",
    courseId: "CS201",
    time: new Date("2025-04-06T17:20:00"),
    isRead: false,
  },
];

export default notificationsData;
